// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/dw-bg/FullBleed.tsx": () => import("../components/mockups/dw-bg/FullBleed.tsx"),
  "./components/mockups/dw-bg/SplitHero.tsx": () => import("../components/mockups/dw-bg/SplitHero.tsx"),
  "./components/mockups/dw-bg/Watermark.tsx": () => import("../components/mockups/dw-bg/Watermark.tsx")
};
